version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users_db
    ports: 
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    container_name: node_api
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    volumes:
      - ./src:/app/src

        
volumes:
  postgres: