version: "3.9"
services:
  postgres:
    container_name: pg_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users_db
    ports: 
      - '2345:5432'
    volumes:
      - ./user_db:/var/lib/postgresql/data

  api:
    container_name: node_api
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    volumes:
      - ./src:/app/src

        
volumes:
  users-db: